name: trickster
description: Social media and spot mapping app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.14.2
  dartz: ^0.9.2
  equatable: ^1.2.5
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  flutter:
    sdk: flutter
  flutter_mobx: ^1.1.0+2
  font_awesome_flutter: ^8.10.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  google_sign_in: ^4.5.5
  injectable: ^0.3.0
  json_serializable: ^3.2.5
  kt_dart: ^0.7.0+1
  mobx: ^1.2.1+3
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  uuid: ^2.2.2

dev_dependencies:
  build_runner: null
  freezed: ^0.12.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^0.3.2
  lint: ^1.2.0
  mobx_codegen: ^1.1.1+1
  mockito: ^4.1.3

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
